<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class RestaurantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('stores')->insert([
            [
                'name' => 'KFC',
                'phone' => '1234567890',
                'email' => 'kfc@example.com',
                'logo' => 'kfc_logo.jpg',
                'latitude' => '37.7749',
                'longitude' => '-122.4194',
                'address' => '123 Main St, San Francisco, CA',
                'footer_text' => 'Finger Lickin’ Good',
                'minimum_order' => 10,
                'comission' => 5,
                'schedule_order' => 1,
                'status' => 1,
                'vendor_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'free_delivery' => 0,
                'rating' => 4.5,
                'cover_photo' => 'kfc_cover.jpg',
                'delivery' => 1,
                'take_away' => 1,
                'slug' => 'kfc',
                'meta_title' => 'KFC',
                'meta_description' => 'Finger Lickin’ Good',
                'module_id' => 1,
            ],
            [
                'name' => 'McDonald\'s',
                'phone' => '0987654321',
                'email' => 'mcdonalds@example.com',
                'logo' => 'mcdonalds_logo.jpg',
                'latitude' => '40.7128',
                'longitude' => '-74.0060',
                'address' => '456 Broadway, New York, NY',
                'footer_text' => 'I’m Lovin’ It',
                'minimum_order' => 15,
                'comission' => 7,
                'schedule_order' => 1,
                'status' => 1,
                'vendor_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'free_delivery' => 1,
                'rating' => 4.7,
                'cover_photo' => 'mcdonalds_cover.jpg',
                'delivery' => 1,
                'take_away' => 1,
                'slug' => 'mcdonalds',
                'meta_title' => 'McDonald\'s',
                'meta_description' => 'I’m Lovin’ It',
                'module_id' => 1,
            ],
            [
                'name' => 'Hardee\'s',
                'phone' => '1122334455',
                'email' => 'hardees@example.com',
                'logo' => 'hardees_logo.jpg',
                'latitude' => '34.0522',
                'longitude' => '-118.2437',
                'address' => '789 Sunset Blvd, Los Angeles, CA',
                'footer_text' => 'Charbroiled Thickburgers',
                'minimum_order' => 12,
                'comission' => 6,
                'schedule_order' => 1,
                'status' => 1,
                'vendor_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'free_delivery' => 1,
                'rating' => 4.3,
                'cover_photo' => 'hardees_cover.jpg',
                'delivery' => 1,
                'take_away' => 1,
                'slug' => 'hardees',
                'meta_title' => 'Hardee\'s',
                'meta_description' => 'Charbroiled Thickburgers',
                'module_id' => 1,
            ],
            [
                'name' => 'Burger King',
                'phone' => '2233445566',
                'email' => 'burgerking@example.com',
                'logo' => 'burgerking_logo.jpg',
                'latitude' => '51.5074',
                'longitude' => '-0.1278',
                'address' => '101 Oxford St, London, UK',
                'footer_text' => 'Have It Your Way',
                'minimum_order' => 10,
                'comission' => 5,
                'schedule_order' => 1,
                'status' => 1,
                'vendor_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'free_delivery' => 0,
                'rating' => 4.4,
                'cover_photo' => 'burgerking_cover.jpg',
                'delivery' => 1,
                'take_away' => 1,
                'slug' => 'burger-king',
                'meta_title' => 'Burger King',
                'meta_description' => 'Have It Your Way',
                'module_id' => 1,
            ],
            [
                'name' => 'Pizza Hut',
                'phone' => '3344556677',
                'email' => 'pizzahut@example.com',
                'logo' => 'pizzahut_logo.jpg',
                'latitude' => '41.8781',
                'longitude' => '-87.6298',
                'address' => '456 State St, Chicago, IL',
                'footer_text' => 'No One Outpizzas the Hut',
                'minimum_order' => 20,
                'comission' => 10,
                'schedule_order' => 1,
                'status' => 1,
                'vendor_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'free_delivery' => 1,
                'rating' => 4.6,
                'cover_photo' => 'pizzahut_cover.jpg',
                'delivery' => 1,
                'take_away' => 1,
                'slug' => 'pizza-hut',
                'meta_title' => 'Pizza Hut',
                'meta_description' => 'No One Outpizzas the Hut',
                'module_id' => 1,
            ],
        ]);
    }
}
